### ISSUE TITLE
Quote component with oversized quotation marks

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/coding-blog-plugin#11]
When I quote documentation, I am satisfied with using a standard [markdown block quote](https://www.markdownguide.org/basic-syntax/#blockquotes-1).

When quoting people, I would prefer if there were some oversized quotations marks.  Here is a [question form tex.stackexchange](https://tex.stackexchange.com/questions/16964/block-quote-with-big-quotation-marks) that contains several answers for how to achieve this look in that context.

What about adding a quotation component to this plugin that includes oversize quotation marks?

**Comment by loreanvictor** [comment]
sounds like a pretty neat idea actually. I might not be able to put in the time for a few weeks, so I would appreciate a PR!

**Comment by loreanvictor** [comment]
[added the component](https://connect-platform.github.io/coding-blog-plugin/misc#quotes), deployed via `0.1.11`.

**Comment by bender2k14** [comment]
That looks great.  Excellent work :)

**Comment by loreanvictor** [comment]
Thanks!
