### ISSUE TITLE
Add small text component for copyright notices or similar text.

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/coding-blog-plugin#12]
The coding.blog plugin currently has a single named font size component called [`Big`](https://connect-platform.github.io/coding-blog-plugin/misc#big-text) and a single customizable horizontal space component called [`Space`](https://connect-platform.github.io/coding-blog-plugin/misc#space).

For font sizes, LaTeX has [ten named sizes](https://en.wikibooks.org/wiki/LaTeX/Fonts#Built-in_sizes) and a [customizable command](https://en.wikibooks.org/wiki/LaTeX/Fonts#Arbitrary_sizes).  For vertical space, LaTex has [three named sizes](http://www.personal.ceu.hu/tex/spacebox.htm#bskip) and one [customizable command](http://www.personal.ceu.hu/tex/spacebox.htm#vspace).

What about adding to this plugin a variety of named size components for font and vertical space and a customizable font size component?

Also, I remembered that `Big` and `Space` existed, but I first went looking for them in CODEDOC instead of this plugin.  Should they be moved to CODEDOC?

**Comment by loreanvictor** [comment]
Its not a matter of supporting or not supporting such customizations, as for example `<span style="font-size: ..."/>` is always available (or you can easily convert it into any custom component). The question is what standard tools should be more conveniently provided (noting that if all possible options are provided then the convenience is definitely gone).

For that matter, I have so far added such components purely based on use-case. Different font-sizes and text styles for example become important much more in blogs than in general programming documents, thats why the components are housed in coding-blog plugin.

I recommend proceeding on the same basis, basically adding components on a use-case basis. Note that the idea of out-of-the-box-available components is to allow authors create beautiful blogposts without them having to think about the details, so for example a _custom font-size_ component doesn't really help (its already there) but _big_ (and perhaps _small_) components that also do support custom font-sizes (perhaps to some degree) do.

**Comment by bender2k14** [comment]
Certainly.  The use case I was considering was small text to add a copyright notification at the the bottom of the TOC.  The normal text size is much too big for that.  I will try using `<span style="font-size: ..."/>`.  Thanks for the reminder.

**Comment by loreanvictor** [comment]
[added the component](https://connect-platform.github.io/coding-blog-plugin/misc#small-text), deployed via `0.1.11`.
