### ISSUE TITLE
Add override option for file publish date when Github is used with Author component

### ISSUE THREAD

**Issue by jamessimone** [CONNECT-platform/coding-blog-plugin#2]
As a content developer, it would be nice to be able to use the "github" option for the Author component while still allowing for configurable dates so that as authors are onboarding onto the platform, they can take advantage of the rich metadata exposed by Github while also exposing the option to override the use of the commit date for a file as its given created date. This will give authors more flexibility when deciding which set of options to provide when using the Author component.

**Comment by jamessimone** [comment]
Such speed! Amazing!

**Comment by loreanvictor** [comment]
Well it was a pretty straight-forward PR! Anyways it is also deployed via `0.1.4`, I also updated the docs and update dependencies on default boilerplate repo of coding.blog. Thanks again!
