### ISSUE TITLE
ArticleCard difference in local vs live hosting

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog-plugin#28]
The [homepage of my live site](https://tysonwilliams.coding.blog/) looks like
![2020-12-02_09-25-10_412_chrome](https://user-images.githubusercontent.com/34664007/100893378-ece7bb00-3480-11eb-8160-1c212c6d5a21.png)

The homepage of my locally hosted site looks like
![2020-12-02_09-25-03_411_chrome](https://user-images.githubusercontent.com/34664007/100893563-199bd280-3481-11eb-81cd-0edd29db891b.png)

That image in the article card is one of the images from my post.  It occurs many times, including as the first image in the post.

Why does that image not show up on my live site?  Can the behavior be changed so that it does show up on the live site?

P.S.
I created issue #25 for a related reason.  I thought the only way to get an image to show up on the article card was if that image was the hero image.  If the behavior of my live site could be changed to match the behavior of my locally hosted site, then I will no longer be blocked by #25.

**Comment by loreanvictor** [comment]
It is interesting that is shows up while hosting locally. Generally article card fetches meta info, and meta image MUST be an absolute URL. #25 will provide a way to automatically create absolute paths from relative asset URLs, which would also alleviate this issue. I will close this issue now since it is basically duplicated by #25.

**Comment by TysonMN** [comment]
Fair enough.  I thought this might be a duplicate, but I created it anyway just to make sure.

**Comment by loreanvictor** [comment]
Always a good idea, I mean there might be cases where two issues overlap but they do have different solutions.
