### ISSUE TITLE
How to add footer icons, not words

### ISSUE THREAD

**Issue by im-coder-lg** [CONNECT-platform/coding-blog-plugin#42]
Whenever I see [<kbd>coding.blog</kbd>](https://coding.blog), the footer icons make me go wow. But whenever I try applying it, it just fails. Is there any method to apply footer icon for GitHub, because I know how to do for RSS. I want only the GitHub icon there, not the GitHub word. How can I do that?

**Comment by loreanvictor** [comment]
[this](https://github.com/CONNECT-platform/coding-blog/blob/master/.codedoc/content/footer.tsx) is how the footer icons are achieved on coding.blog website, I suspect simply copying that and removing the icons you don't want gets the expected result.

**Comment by im-coder-lg** [comment]
I tried it before and it didn't go too well for me. I will try it again.

**Comment by im-coder-lg** [comment]
Yeah, works! Can I do the same for RSS too?

**Comment by loreanvictor** [comment]
depends on how you want to add an RSS icon. this is how I do it on my own blog:

```jsx
<a href="https://eugene.coding.blog/_feed.rss" target="_blank"><Icon>rss_feed</Icon>RSS</a>
```
which means the RSS icon is from the icon-font. however, the icons on coding.blog's footer are images (vectors), two overlayed on top of each other (for light and dark mode). so it is possible you would need to do some CSS / styling tinkering to get it work properly, if the icon from the icon-font actually matches your svg icon styles.

**Comment by im-coder-lg** [comment]
Oh yeah, I figured it out. I used the same method I used for the GitHub Icon. Similarly, I did for my Matrix and Gitter and it does work. All it actually needs is an SVG, so I got some. Thanks for helping me!

**Comment by im-coder-lg** [comment]
The theme you use on coding.blog is the one I use, since I realized that I need a lighter dark mode, and it fits very well. I say that light and dark mode combined is the coding.blog dark mode.

**Comment by im-coder-lg** [comment]
Glitch alert: I added GitHub, RSS, Matrix and Gitter via the same method. But the SVGs are not loading. But in my cloud Gitpod, they work. What should I do?

**Comment by im-coder-lg** [comment]
no worries @loreanvictor i solved it va the ROOT directory path including the `./` thing, and it works successfully! Thanks for all the help!
