### ISSUE TITLE
Support for tags

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/coding-blog-plugin#8]
Eventually I would like to add tags to my blog.

Is there any desire to add tagging support to this plugin?

**Comment by loreanvictor** [comment]
Yes. Sort of. You can add SEO keywords, which are also ignored by Google apparently these days. Besides that, tags would be nice for categorization of the content, but that can be done relatively nicely with some NLP instead of putting the responsibility on author's shoulders.

So how do you envision tags, like in what capacity or for what purpose?

**Comment by bender2k14** [comment]
I never think about SEO.  My motivation is categorization.  As a (future!) coding.blog author, I don't mind shouldering some responsibility and picking some tags myself.  Auto-generating tags via NLP is also a good idea.  I even think having both at the same time could be good.

As an author, I like forcing myself to pick tags because I think it helps me think about the bigger picture.  Sort of like how it is easy to ramble on in a post, but harder to write the introduction, and even harder to write an abstract, and even harder to write the title.  In the same way, picking tags helps me put myself into the frame of mind of my readers.

**Comment by loreanvictor** [comment]
Convinced. Will add a `:Tags` component working like this:

```md
> :Tags
>
> programming, web, cloud, NLP, whatever, ...
```

For now it will only display the tags and add them to both `keywords` meta and a separate meta-tag which is going to be read by `coding.blog` later for further categorization. In the future, perhaps the tags should be auto-linked to corresponding search pages on `coding.blog`, though this won't affect the plugin code itself (perhaps it should be a post-processor injected in `coding.blog`'s build pipeline, so that it doesn't link to that page when deployed on other environments).

**Comment by bender2k14** [comment]
> In the future, perhaps the tags should be auto-linked to corresponding search pages on `coding.blog`...

Oh, that is an interesting way to strengthen your platform.  I like it.

For the default behavior though, I would prefer the search result page be filtered to pages from the author's blog from which the tag was clicked.  From there, one more simple click to remove the author filter would give the search results for pages from all sites hosted on `coding.blog`.

**Comment by loreanvictor** [comment]
> For the default behavior though, I would prefer the search result page be filtered to pages from the author's blog from which the tag was clicked. From there, one more simple click to remove the author filter would give the search results for pages from all sites hosted on `coding.blog`

For authors with lots of content, that makes sense. We should see how many of authors will have that amount of content that dedicated search functionality across their blog would be useful.

**Comment by bender2k14** [comment]
Good point.  To improve the behavior for authors with less content, the behavior in all cases could be to "sort" instead of filter by the author.  So all that author's content would be first, then (I would prefer) a short gap or something to indicate the primary author's content has ended, then search results from all other authors on `coding.blog`.

**Comment by loreanvictor** [comment]
deployed via `0.1.10`

**Comment by loreanvictor** [comment]
also [added to docs](https://connect-platform.github.io/coding-blog-plugin/tags).

**Comment by bender2k14** [comment]
Is there a certain way to update dependencies like this?

To update `codedoc/core`, I execute `codedoc update latest --local`.  I executed that command, but it didn't change `codedoc/coding-blog-plugin`.  I know I could just put `0.1.10` in my `package.json` file, delete my `package.json.lock` file, and execute `codedoc install`, but this doesn't seem like the best way to achieve the desired outcome.

**Comment by loreanvictor** [comment]
> Is there a certain way to update dependencies like this?
> 
> To update `codedoc/core`, I execute `codedoc update latest --local`. I executed that command, but it didn't change `codedoc/coding-blog-plugin`. I know I could just put `0.1.10` in my `package.json` file, delete my `package.json.lock` file, and execute `codedoc install`, but this doesn't seem like the best way to achieve the desired outcome.

does this work?

```bash
cd .codedoc && npm update
```

**Comment by loreanvictor** [comment]
either way it is (at least a bit) inconvenient right now to update plugins, so I created [this issue](https://github.com/CONNECT-platform/codedoc-cli/issues/2) to make the process smoother.

**Comment by bender2k14** [comment]
`npm update` didn't do anything but `npm i @codedoc/coding-blog-plugin` worked.  Thanks! :)

**Comment by loreanvictor** [comment]
ok the CLI is updated (`0.2.2`) and from now on you should be able to update this plugin via:

```bash
codedoc update plugins
```

or 

```bash
codedoc install @codedoc/coding-blog-plugin
```

**Comment by bender2k14** [comment]
`codedoc update plugins` didn't do anything for me but `codedoc install @codedoc/coding-blog-plugin` did.

```
twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (update_README)
$ codedoc -v

# Fetching version info ...
# @codedoc/cli version 0.2.2 ...................................... latest: 0.2.2
# @codedoc/core version: 0.2.10 ................................... latest: 0.2.10


twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (update_README)
$ codedoc update plugins

# Updating plugins ...


twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (update_README)
$ codedoc install @codedoc/coding-blog-plugin

# Installing plugins ...
npm WARN ts-loader@6.2.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN .codedoc No description
npm WARN .codedoc No repository field.
npm WARN .codedoc No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @codedoc/coding-blog-plugin@0.1.10
updated 2 packages and audited 599 packages in 5.723s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
